# Generated by Django 5.0 on 2023-12-13 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "Id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("publishDate", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "eID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("firstName", models.CharField(max_length=50)),
                ("middleName", models.CharField(blank=True, max_length=50, null=True)),
                ("lastName", models.CharField(max_length=50)),
                ("phoneNo", models.CharField(max_length=12, unique=True)),
                ("email", models.EmailField(max_length=70, unique=True)),
                ("addharNo", models.CharField(max_length=20, unique=True)),
                ("dOB", models.DateField()),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("HR Department", "HR Department"),
                            ("Procurements Department", "Procurements Department"),
                            ("Execution Department", "Execution Department"),
                            ("IT Department", "IT Department"),
                            ("Intern", "Intern"),
                            ("Sales Department", "Sales Department"),
                            ("Co-Founder", "Co-Founder"),
                            ("PC Team", "PC Team"),
                        ],
                        max_length=50,
                    ),
                ),
                ("salary", models.CharField(max_length=20)),
                ("joinDate", models.DateField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("January", "January"),
                            ("February", "February"),
                            ("March", "March"),
                            ("April", "April"),
                            ("May", "May"),
                            ("June", "June"),
                            ("July", "July"),
                            ("August", "August"),
                            ("September", "September"),
                            ("October", "October"),
                            ("November", "November"),
                            ("December", "December"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "days",
                    models.CharField(
                        choices=[
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                            ("16", "16"),
                            ("17", "17"),
                            ("18", "18"),
                            ("19", "19"),
                            ("20", "20"),
                            ("21", "21"),
                            ("22", "22"),
                            ("23", "23"),
                            ("24", "24"),
                            ("25", "25"),
                            ("26", "26"),
                            ("27", "27"),
                            ("28", "28"),
                            ("29", "29"),
                            ("30", "30"),
                            ("31", "31"),
                        ],
                        max_length=5,
                    ),
                ),
                ("time", models.TimeField(blank=True, null=True)),
                (
                    "eId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Requests",
            fields=[
                (
                    "request_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("requestMessage", models.TextField()),
                ("requestDate", models.DateTimeField()),
                (
                    "destinationEmployeeId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toEmployeeId",
                        to="employee.employee",
                    ),
                ),
                (
                    "requesterId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requesterId",
                        to="employee.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalaryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("January", "January"),
                            ("February", "February"),
                            ("March", "March"),
                            ("April", "April"),
                            ("May", "May"),
                            ("June", "June"),
                            ("July", "July"),
                            ("August", "August"),
                            ("September", "September"),
                            ("October", "October"),
                            ("November", "November"),
                            ("December", "December"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "days",
                    models.CharField(
                        choices=[
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                            ("14", "14"),
                            ("15", "15"),
                            ("16", "16"),
                            ("17", "17"),
                            ("18", "18"),
                            ("19", "19"),
                            ("20", "20"),
                            ("21", "21"),
                            ("22", "22"),
                            ("23", "23"),
                            ("24", "24"),
                            ("25", "25"),
                            ("26", "26"),
                            ("27", "27"),
                            ("28", "28"),
                            ("29", "29"),
                            ("30", "30"),
                            ("31", "31"),
                        ],
                        max_length=5,
                    ),
                ),
                ("time", models.TimeField(blank=True, null=True)),
                ("net_amount", models.IntegerField()),
                ("credited", models.IntegerField(blank=True, null=True)),
                ("pending_amount", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Clear", "Clear"),
                            ("Advance", "Advance"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="workAssignments",
            fields=[
                (
                    "assignment_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("work", models.TextField()),
                ("assignDate", models.DateTimeField()),
                ("dueDate", models.DateTimeField()),
                (
                    "assignerId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignerId",
                        to="employee.employee",
                    ),
                ),
                (
                    "taskerId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskerId",
                        to="employee.employee",
                    ),
                ),
            ],
        ),
    ]
